### ISSUE TITLE
Segmentation Support

### ISSUE THREAD

**Issue by amitbcp** [lemonci/IIC_c#1]
I was trying to experiment with IIC, and was looking for a more new build with Python3 & pytorch >=1.0
I cam across the repository. Thanks for open sourcing it.
Could you please help me to understand , does the implementation support segmentation and pytorch>1.0 ?

**Comment by lemonci** [comment]
This repo is for python 2.
Please refer to https://github.com/sebastiani/IIC for python 3 and pytorch 1.0
